=== Roy-Rebuffo/repasoExamenXML3erTrimestre/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"></xs:element>
                            <xs:element name="autor">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="pais" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="anio" type="xs:gYear"/>
                            <xs:element name="genero" type="xs:string"/>
                            <xs:element name="idioma" type="xs:string" minOccurs="0"/>
                            <xs:element name="edicion" type="xs:string" minOccurs="0"/>
                            <xs:element name="devolucion" type="xs:date" minOccurs="0"/>
                            <xs:element name="sinopsis" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="prestado">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="sÃ­"></xs:enumeration>
                                    <xs:enumeration value="no"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>      
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/repasoExamenXML3erTrimestre/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?> 
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    <libro prestado="sí">
        <titulo>El nombre del viento</titulo>
        <autor pais="EEUU">Patrick Rothfuss</autor>
        <anio>2007</anio>
        <genero>Fantasía</genero>
        <idioma>Inglés</idioma>
        <edicion>Primera</edicion>
        <devolucion>2025-06-15</devolucion>
        <sinopsis>Crónica del asesino de reyes, historia de Kvothe.</sinopsis>
    </libro>

    <libro prestado="no">
        <titulo>Cien años de soledad</titulo>
        <autor pais="Colombia">Gabriel García Márquez</autor>
        <anio>1967</anio>
        <genero>Realismo mágico</genero>
        <sinopsis></sinopsis>
    </libro>

    <libro prestado="no">
        <titulo>Don Quijote de la Mancha</titulo>
        <autor pais="España">Miguel de Cervantes</autor>
        <anio>1605</anio>
        <genero>Novela</genero>
        <idioma>Español</idioma>
        <edicion>Edición académica</edicion>
        <sinopsis></sinopsis>
    </libro>
</biblioteca>
