=== Roy-Rebuffo/repasoExamenXML3erTrimestre/empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleados" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre"></xs:element>
                                        <xs:element name="edad"></xs:element>
                                        <xs:element name="departamento"></xs:element>
                                        <xs:element name="incorporacion"></xs:element>
                                        <xs:element name="email" minOccurs="0"></xs:element>
                                        <xs:element name="telefono" minOccurs="0"></xs:element>
                                        <xs:element name="observaciones" minOccurs="0"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="dni" type="xs:string" /> <!-- atributo de empleado -->
                                    <xs:attribute name="estado"> <!-- atributo de empleado -->
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="activo"></xs:enumeration>
                                                <xs:enumeration value="inactivo"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="jefe"> <!-- atributo de empleado -->
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="si"></xs:enumeration>
                                                <xs:enumeration value="no"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Roy-Rebuffo/repasoExamenXML3erTrimestre/empresa.xml
<?xml version="1.0" encoding="UTF-8"?> 
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="empresa.xsd">
    <empleados>
        <empleado dni = "X7233395X" estado="activo" jefe = "si">
        <nombre>Roy</nombre>           
        <edad>Rebuffo</edad>
        <departamento >BackEnd</departamento>
        <incorporacion>19/05/2025</incorporacion>
        <email>royci98@icloud.com</email>
        <telefono>618588855</telefono>
        <observaciones>Gran currante</observaciones><!--elemento opcional y puede estar vacio-->
        </empleado>
    </empleados>
</empresa>
